config/routes.rb
Rails.application.routes.draw do

  post 'galleries/trash' => 'galleries#trash'
  resources :galleries
  resources :pictures
  post 'users/:id/upgrade' => 'users#admin', as: :upgrade
  post 'users/:id/downgrade' => 'users#downgrade', as: :downgrade
  devise_for :users
  resources :users
  get 'news' => 'posts#news', as: :news
  resources :posts

  root 'posts#news'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:rememberable#, :registerable,
         #:recoverable,
         # :trackable, :validatable
  validates :name, :last_name, presence: true
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "avatar.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  after_destroy :ensure_an_admin_remains
  after_update :ensure_an_admin_remains
  has_many :posts


  private
  def ensure_an_admin_remains
    if User.where(admin: true).count.zero?
      raise "Can't delete last admin"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :admin]
  load_and_authorize_resource
  # before_action :authenticate_user!
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def admin
    @user.admin=true
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully upgraded to admin.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def downgrade
    @user.admin=false
    begin
      @user.save!
      flash[:notice] =  'Admin was successfully downgraded to user.'
    rescue StandardError => ex
      flash[:notice] = ex.message
    end
      respond_to do |format|
      format.html { redirect_to user_path(@user) }
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    begin
      @user.destroy
      flash[:notice] = "User #{@user.name} #{@user.last_name} deleted"
    rescue StandardError => ex
      flash[:notice] = ex.message
    end
    respond_to do |format|
        format.html { redirect_to users_url }
        format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nickname, :password, :password_confirmation, :name, :last_name, :avatar, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user", multipart: true } do |f| %>

    <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:last_name]) %>
    <div class="control-group">
      <%= f.label :avatar, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :avatar, :class => 'form-control' %>
      </div>
      <%= error_span(@user[:avatar]) %>
    </div>
    <%= error_span(@user[:avatar_updated_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.email_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:email]) %>
  </div>
    <div class="control-group">
      <%= f.label :password, 'Password', :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :class => 'form-control' %>
      </div>
      <%= error_span(@user[:password]) %>
    </div>
    <div class="control-group">
      <%= f.label :password_confirmation, 'Confirm', :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, :class => 'form-control' %>
      </div>
      <%= error_span(@user[:password_confirmation]) %>
    </div>



  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            users_path, :class => 'btn btn-default' %>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:last_name) %></th>
    <th><%= model_class.human_attribute_name(:avatar) %></th>
    <th><%= model_class.human_attribute_name(:email) %></th>
    <% if can? :admin, User %>
        <th><%= model_class.human_attribute_name(:admin) %></th>
    <% end %>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= image_tag user.avatar.url(:thumb) %></td>
        <td><%= user.email %></td>
        <% if can? :admin, User %>
            <td><%= user.admin %></td>
        <% end %>
        <td>
          <% if can? :edit, user %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <% end %>
          <% if can? :destroy, user %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          user_path(user),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<% if can? :create, User %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_user_path,
                :class => 'btn btn-primary' %>
<% end %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @user.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar) %>:</strong></dt>
  <dd><%= image_tag @user.avatar.url(:thumb)%></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>

  <% if can? :admin, @user %>
      <dt><strong><%= model_class.human_attribute_name(:admin) %>:</strong></dt>
      <dd><%= @user.admin %></dd>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
            users_path, :class => 'btn btn-default'  %>

<% if can? :edit, @user %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_user_path(@user), :class => 'btn btn-default' %>
<% end %>

<% if can? :destroy, @user %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                user_path(@user),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% end %>


<% if can? :admin, @user %>
    <% if @user.admin? %>
        <%= link_to t('.DowngradeAdmin'), downgrade_path(@user),
                    method: 'downgrade',
                    class: 'btn btn-success' %>
    <% else %>
        <%= link_to t('.makeAdmin'), upgrade_path(@user),
                    method: 'admin',
                    class: 'btn btn-success' %>
    <% end %>
<% end %>