config/routes.rb
Rails.application.routes.draw do

  post 'galleries/trash' => 'galleries#trash'
  resources :galleries
  resources :pictures
  post 'users/:id/upgrade' => 'users#admin', as: :upgrade
  post 'users/:id/downgrade' => 'users#downgrade', as: :downgrade
  devise_for :users
  resources :users
  get 'news' => 'posts#news', as: :news
  resources :posts

  root 'posts#news'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :gallery

  has_attached_file :image, styles: { medium: "300x300>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:image, :title, :description, :gallery_id)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for @picture, :html => { :class => "form-horizontal picture" } do |f| %>

    <% if @picture.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

    <%= image_tag @picture.image.url(:medium) %>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image, :class => 'form-control' %>
    </div>
    <%= error_span(@picture[:image_updated_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@picture[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@picture[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :gallery_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :gallery_id, options_for_select(Gallery.all.map{ |o| ["#{o.title}", o.id]}), :class => 'form-control' %>
    </div>
    <%= error_span(@picture[:gallery_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            pictures_path, :class => 'btn btn-default' %>

<% end %>

app/views/pictures/edit.html.erb
<%- model_class = Picture -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pictures/index.html.erb
<%- model_class = Picture -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:gallery_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= link_to picture.id, picture_path(picture) %></td>
        <td><%= image_tag picture.image.url(:medium) %></td>
        <td><%= picture.title %></td>
        <td><%= picture.description %></td>
        <td><%= link_to picture.gallery.title, gallery_path(picture.gallery_id) %></td>
        <td><%=l picture.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_picture_path(picture), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      picture_path(picture),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_picture_path,
            :class => 'btn btn-primary' %>

app/views/pictures/new.html.erb
<%- model_class = Picture -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pictures/show.html.erb
<%- model_class = Picture -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag @picture.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @picture.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @picture.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gallery_id) %>:</strong></dt>
  <dd><%= link_to @picture.gallery.title, gallery_path(@picture.gallery) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
            gallery_path(@picture.gallery), :class => 'btn btn-default'  %>
<% if can? :edit, Picture %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_picture_path(@picture), :class => 'btn btn-default' %>
<% end %>
<% if can? :destroy, Picture %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            picture_path(@picture),
            :method => 'delete',
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-danger' %>
<% end %>