config/routes.rb
Rails.application.routes.draw do

  post 'galleries/trash' => 'galleries#trash'
  resources :galleries
  resources :pictures
  post 'users/:id/upgrade' => 'users#admin', as: :upgrade
  post 'users/:id/downgrade' => 'users#downgrade', as: :downgrade
  devise_for :users
  resources :users
  get 'news' => 'posts#news', as: :news
  resources :posts

  root 'posts#news'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :title, :body, presence: true
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }
  has_attached_file :clip,:styles => {
                             :medium => { :geometry => "640x480", :format => 'ogg'},
                             :poster => { geometry: "640x480", format: 'jpg', time: 10},
                             :thumb => { :geometry => "100x100#", :format => 'jpg', :time => 15 }
                         }, :processors =>  [:transcoder],
                    :use_timestamp => false
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :clip, content_type: /\Avideo\/.*\Z/

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: [:show, :index, :news]
  load_and_authorize_resource
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def news
    @posts = Post.order(created_at: :desc).where(news_page: true)
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
      @post = Post.find(params[:id])
    end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
      params.require(:post).permit(:title, :body, :picture, :clip, :news_page)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>

    <% if @post.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @post.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>
      <%= error_span(@post[:title]) %>
    </div>
    <div class="control-group">
      <%= f.label :body, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :body, :class => 'form-control' %>
      </div>
      <%= error_span(@post[:body]) %>
    </div>
    <div class="control-group">
      <%= f.label :picture, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :picture %>
      </div>
      <%= error_span(@post[:picture]) %>
    </div>
    <div class="control-group">
      <%= f.label :clip, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :clip %>
      </div>
      <%= error_span(@post[:clip]) %>
    </div>
    <div class="control-group">
      <%= f.label :news_page, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :news_page %>
      </div>
      <%= error_span(@post[:clip]) %>
    </div>


    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn btn-default' %>

<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:author) %></th>
    <th><%= model_class.human_attribute_name(:title) %></th>
    <th><%= model_class.human_attribute_name(:body) %></th>
    <th><%= model_class.human_attribute_name(:picture) %></th>
    <th><%= model_class.human_attribute_name(:clip) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= link_to "#{post.user.name} #{post.user.last_name}", user_path(post.user) %></td>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= image_tag post.picture.url(:thumb) %></td>
        <td><%= image_tag post.clip.url(:thumb) %></td>

        <td><%=l post.created_at %></td>
        <td>
          <% if can? :update, post %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_post_path(post), :class => 'btn btn-default btn-xs' %>
          <% end %>
          <% if can? :destroy, post %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
            <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/news.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => "News" %></h1>
</div>
<!--https://github.com/IronSummitMedia/startbootstrap-blog-post/blob/gh-pages/index.html-->
<div class="container">
  <% @posts.each do |post| %>
    <div class="row">
        <h2><%= post.title %></h2>
      <p class="lead">
        by <%= link_to "#{post.user.name} #{post.user.last_name}", user_path(post.user) %>
        <!--by <a href="#">Start Bootstrap</a>-->
      </p>
      <hr>
      <!-- Date/Time -->
      <p><span class="glyphicon glyphicon-time"></span> <%= post.created_at.strftime("%d. %B, %Y") %></p>
      <hr>
      <% if post.picture.exists?%>
          <%= image_tag post.picture.url %>
          <hr>
      <% end  %>
      <% if post.clip.exists?%>
          <%= video_tag post.clip.url(:medium), controls: true, poster: post.clip.url(:poster), height: 180 %>
          <hr>
      <% end  %>

      <p><%= post.body %></p>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Author) %>:</strong></dt>
  <dd><%= link_to "#{@post.user.name} #{@post.user.last_name}", user_path(@post.user) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @post.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:picture) %>:</strong></dt>
  <dd><%= image_tag @post.picture.url(:thumb) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:clip) %>:</strong></dt>
  <% if @post.clip.exists? %>
  <dd> <%= video_tag @post.clip.url(:medium), controls: true, type: 'video/ogg', poster: @post.clip.url(:poster), width: 320 ,height:240, autobuffer: true%></dd>
  <% else %>
  <dd>Missing</dd>
  <% end %>
  <dt><strong><%= model_class.human_attribute_name(:news_page) %>:</strong></dt>
  <% unless @post.news_page.nil? %>
      <dd> <%= @post.news_page %></dd>
  <% else %>
      <dd> nope </dd>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
            posts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            post_path(@post),
            :method => 'delete',
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-danger' %>