config/routes.rb
Rails.application.routes.draw do

  post 'galleries/trash' => 'galleries#trash'
  resources :galleries
  resources :pictures
  post 'users/:id/upgrade' => 'users#admin', as: :upgrade
  post 'users/:id/downgrade' => 'users#downgrade', as: :downgrade
  devise_for :users
  resources :users
  get 'news' => 'posts#news', as: :news
  resources :posts

  root 'posts#news'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zeltlager Oberndorf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class = '<%= controller.controller_name %>'>
<nav class = "navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%# link_to root_path do %>
          <%# image_tag("logo.png", size: "45x45", alt:"Icon") %>
      <%# end %>
      <%= link_to "Zeltlager Oberndorf", root_path, class: "navbar-brand"%>
      <div class="btn-group">
        <button type="button" data-toggle="dropdown" class="btn btn-default navbar-btn dropdown-toggle">Galleries <span class="caret"></span></button>
        <ul class="dropdown-menu">
          <% Gallery.all.each do |gallery| %>
          <li><%= link_to gallery.title, gallery_path(gallery) %></li>
          <% end %>
        </ul>
      </div>
      <% if current_user.present? %>
          <%= link_to 'Galleries', galleries_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Posts', posts_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete , class: 'btn navbar-btn navbar-inverse pull-right'%>
          <%= link_to 'Users', users_path , class: 'btn btn-default navbar-btn pull-right'%>
          <p class="navbar-text pull-right"> </p>
          <p class="navbar-text pull-right">Hello <%= current_user.name %></p>
      <% else  %>
          <%= link_to 'Sign Up', new_user_path, class: 'btn btn-success navbar-btn pull-right' %>
          <%= link_to 'Login', new_user_session_path, class: 'btn navbar-btn navbar-inverse pull-right' %>
      <%end%>
    </div>
  </div>
</nav>

<div id="main" class="container">
  <%= flash_messages %>

  <%= yield %>
</div>

</body>
</html>